### ISSUE TITLE
Image links broken in share cards

### ISSUE THREAD

**Issue by genebean** [statichunt/iwriter-hugo#12]
It seems building a site causes files like assets/images/foo.png to be converted to webp but the templates for twitter:image and og:image don’t account for this. They are still looking for /images/foo.png, which 404’s.

**Comment by tfsojon** [comment]
Hello @genebean 
We published a new version of iWriter. This Issue is solved with new release [v2.0.0](https://github.com/statichunt/iwriter-hugo/releases/tag/v2.0.0)

**Comment by genebean** [comment]
@tfsojon it appears some amount of work is needed for exiting users to update to v2.0.0 based on [this PR by dependabot](https://github.com/genebean/hugo-volunteertechnologist.com/pull/19#issuecomment-1396813946) failing to build on Netlify. Are there any docs on how to go about updating?

**Comment by genebean** [comment]
I ended up filing https://github.com/statichunt/iwriter-hugo/issues/13 about this issue @tfsojon

**Comment by tfsojon** [comment]
@genebean As you can see [v2.0.0](https://github.com/statichunt/iwriter-hugo/releases/tag/v2.0.0) is a huge upgrade so creating a step by step upgrade guide will be quite messy. For now please follow the Commits on Jan 19, 2023
- 8937878025fc5eab59d01ba742ffbdc54ee22779
- afd1c2f4171d7440e0142b9558f38c704c0afd79
- 76e843ceeee32705129331eac912a83eaedbdbaa
- 4b240da7f1689a25ae5057f0d954d9f95767acea
- 0a921cf577a1e6449e6daff332cb6c9eb8248fcb
- 57f572b841190c81b1d7d84b85df3286c211c1c6
