### ISSUE TITLE
Full documentation link broken?

### ISSUE THREAD

**Issue by joshuar** [statichunt/iwriter-hugo#19]
Hey there,

Nice theme! It looks like the link to the full documentation in the `README.md` is broken. I tried to search around on https://docs.gethugothemes.com but it doesn't seem to be there? Is there a different location for this themes specific documentation?

Cheers!

**Comment by tfsomrat** [comment]
Hey @joshuar 

It looks like we didn't have this documentation. but you can follow our [universal guide](https://docs.gethugothemes.com/guide/) to get started. thanks

**Comment by joshuar** [comment]
Coolio, thanks @tfsomrat for the clarification!
