### ISSUE TITLE
Button on homepage doesn't work

### ISSUE THREAD

**Issue by genebean** [statichunt/iwriter-hugo#5]
The example site includes `link: "/"` as the parameter that controls the target url for the optional button at the top but, based on what I see at the link below, that is not correct. 
https://github.com/statichunt/iwriter-hugo/blob/d9d45ed7a917727f3380170893564f11380f26ac/layouts/index.html#L18

I think `link` is what the setting should be and I think it should support both relative or external links... I am not exactly sure how best to fix this... maybe just pipe it through the `abs` function?

**Comment by genebean** [comment]
Many thanks!

**Comment by tfsojon** [comment]
You are always welcome @genebean and thank you for let us know about the issue!
